###findAll
GET http://localhost:8080/discountCards?pageNumber=1&pageSize=3
Accept: application/json

###findById
GET http://localhost:8080/discountCards?id=2
Accept: application/json

###save
POST http://localhost:8080/discountCards
Content-Type: application/json

{
  "discountCardNumber": "5689",
  "discountPercentage": 6
}

###findByDiscountCardNumber
GET http://localhost:8080/discountCards?discountCardNumber=5689
Accept: application/json

###delete
DELETE http://localhost:8080/discountCards?id=4
Content-Type: application/json
